{application,ops,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{ops_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[cluster,cluster_data,dist_lib,ops,ops_app,ops_lib,
                        ops_sup,pod,service]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
